apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: md297dvrp-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/md297dvrp-java-springboot-gitops